syntax = "proto3";

package ua.gov.diia.types.ds.organisms;

import "designSystem/molecules/tableItemHorizontalMlc.proto";
import "ui.proto";

option java_multiple_files = true;
option java_package = "ua.gov.diia.types.ds.organisms";

/**
 @see https://diia.atlassian.net/wiki/spaces/DIIA/pages/3184198145/tableItemCascadeOrg
*/
message TableItemCascadeOrg {
  optional string componentId = 1;
  optional ua.gov.diia.types.ds.PaddingMode paddingMode = 2;
  optional ua.gov.diia.types.ds.molecules.TableItemHorizontalMlc tableItemHorizontalMlc = 3;
  repeated Item items = 4;

  message Item {
    optional ua.gov.diia.types.ds.molecules.TableItemHorizontalMlc tableItemHorizontalMlc = 1;
  }
}
