syntax = "proto3";

package ua.gov.diia.types.ds.molecules;

import "ui.proto";

option java_multiple_files = true;
option java_package = "ua.gov.diia.types.ds.molecules";

/**
 * @see
 * https://diia.atlassian.net/wiki/spaces/DIIA/pages/2992603298/inputDateMlcV2
 */
message InputDateMlcV2 {
  string componentId = 1;
  optional string inputCode = 2;
  optional string placeholder = 3;
  string label = 4;
  optional string value = 5;
  optional string hint = 6;
  optional bool mandatory = 7;
  optional ua.gov.diia.types.ds.PaddingMode paddingMode = 8;
}
