syntax = "proto3";

package ua.gov.diia.types.ds.molecules;

import "designSystem/atoms/buttonAction.proto";
import "designSystem/atoms/iconUrlAtm.proto";
import "ui.proto";

option java_multiple_files = true;
option java_package = "ua.gov.diia.types.ds.molecules";

/**
 * @see https://diia.atlassian.net/wiki/spaces/DIIA/pages/3192488412/miniCardMlc
 */
message MiniCardMlc {
  string componentId = 1;
  optional ua.gov.diia.types.ds.PaddingMode paddingMode = 2;
  string label = 3;
  optional string description = 4;
  optional string icon = 5;
  optional ua.gov.diia.types.ds.atoms.IconUrlAtm iconUrlAtm = 6;
  optional ua.gov.diia.types.ds.atoms.button.ButtonAction action = 7;
}
